#MD013 - Line length
line-length:
  line_length: 1600
  heading_line_length: 160
  code_block_line_length: 120
  tables: false

# MD025 - Multiple top-level headings in the same document
single-title:
  front_matter_title: ""

no-hard-tabs:
  ignore_code_languages: [
    "console"
  ]

