name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: deploy-hugo
  cancel-in-progress: true

jobs:
  build-site:
    name: Render static site with Hugo
    runs-on: ubuntu-latest

    steps:
      - id: checkout-branch
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - id: install-hugo
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      # Uncomment the sections below for any sites that have npm dependencies.
      # - id: configure-npm-cache
      #   name: Configure npm caching
      #   uses: c-hive/gha-npm-cache@v1
      # - id: install-npm-deps
      #   name: Install npm dependencies
      #   run: npm install

      # Build the site with Hugo, explicity declaring the production environment,
      # minification, and garbage collection.
      - id: build-site
        name: Build static site with Hugo
        run: hugo --environment production --gc --minify --logFile hugo-build.log --verboseLog

      # Save the build log for this workflow run
      - id: store-logs
        name: Store Hugo build log
        uses: actions/upload-artifact@v2
        with:
          name: hugo-build-log
          path: hugo-build.log

      - id: tar-build-dir
        run: |
          cd ${GITHUB_WORKSPACE}/public/
          tar -cvf ${GITHUB_WORKSPACE}/public.tar .

      # Save the build artifacts for this workflow run
      - id: store-build
        name: Store Hugo build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hugo-site
          path: public.tar

  deploy-site:
    name: Deploy the rendered site
    runs-on: ubuntu-latest
    needs: [build-site]
    concurrency:
      group: deploy-hugo-to-pages
      cancel-in-progress: false

    steps:
      # Get a truncated commit hash for the current commit to include in the
      # commit message for the deployment commit.
      - id: truncated-hash
        name: Set truncated SHA hash for deployment commit message
        run: echo "short_hash=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - id: checkout-ghpages
        name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/heads/gh-pages
          path: repo

      - id: download-build
        name: Download Hugo build artifacts
        uses: actions/download-artifact@v2
        with:
          name: hugo-site

      - id: untar-build-dir
        name: Untar Hugo build directory
        run: |
          mkdir ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          tar -xvf ${GITHUB_WORKSPACE}/public.tar

      - id: commit-changes
        name: Commit changes to Pages deployment
        run: |
          cd ${GITHUB_WORKSPACE}/build
          export GIT_DIR="${GITHUB_WORKSPACE}/repo/.git"

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git status
          git add .
          git commit -m "[${{ env.short_hash }}] ${{ github.event.head_commit.message }}"
          git push

      # - id: deploy-pages
      #   name: Deploy static site to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}  # automatic
      #     publish_dir: ./public  # where rendered site can be found for deployment
      #     publish_branch: gh-pages  # which branch the site should be deployed to
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"
      #     full_commit_message: "[${{ env.short_hash }}] ${{ github.event.head_commit.message }}"
      #     allow_empty_commit: true  # record all deployment attempts
